fix: info when file can't be stripped

diff --git a/rootfs/usr/local/bin/.eleven/strip b/rootfs/usr/local/bin/.eleven/strip
--- a/rootfs/usr/local/bin/.eleven/strip
+++ b/rootfs/usr/local/bin/.eleven/strip
@@ -12,7 +12,10 @@
       eleven log info "${1} was shrunk by ${BYTES_PERCENT}%!"
     else
       eleven log warning "could not find file [${1}]"
+      exit 1
     fi
+  else
+    eleven log warning "can't strip ${1}"
   fi
 
   exit 0
