[fix] do not shrink .so files

diff --git a/rootfs/usr/local/bin/.eleven/strip b/rootfs/usr/local/bin/.eleven/strip
--- a/rootfs/usr/local/bin/.eleven/strip
+++ b/rootfs/usr/local/bin/.eleven/strip
@@ -1,15 +1,17 @@
 #!/bin/sh
   # eleven strip /path/to/binary/to/be/stripped
 
-  if [ -f "${1}" ]; then
-    BYTES_START=$(du -b ${1} | cut -f1)
-    strip -v ${1} &> /dev/null
-    upx -q ${1} &> /dev/null
-    BYTES_END=$(du -b ${1} | cut -f1)
-    BYTES_PERCENT=$((100 - (200*${BYTES_END}/${BYTES_START} % 2 + 100*${BYTES_END}/${BYTES_START})))
-    eleven log info "${1} was shrunk by ${BYTES_PERCENT}%!"
-  else
-    eleven log warning "could not find file [${1}]"
+  if ! echo "${1}" | grep -q ".so"; then
+    if [ -f "${1}" ]; then
+      BYTES_START=$(du -b ${1} | cut -f1)
+      strip -v ${1} &> /dev/null
+      upx -q ${1} &> /dev/null
+      BYTES_END=$(du -b ${1} | cut -f1)
+      BYTES_PERCENT=$((100 - (200*${BYTES_END}/${BYTES_START} % 2 + 100*${BYTES_END}/${BYTES_START})))
+      eleven log info "${1} was shrunk by ${BYTES_PERCENT}%!"
+    else
+      eleven log warning "could not find file [${1}]"
+    fi
   fi
 
   exit 0
